---
 - name: "add repo"
   become: true
   shell: "curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -"
 
 - name: "update apt packages."
   become: true
   yum:
     update_cache: yes

 - name: "upgrade packages"
   become: true
   yum:
     name: '*'
     state: latest

 - name: "install dependencies"
   become: true
   yum:
     name: ["nodejs","python37"]
     state: latest
     update_cache: yes

 - name: "install pm2"
   become: true
   npm:
     name: pm2
     global: yes
     production: yes
     state: present