
- name: "Extract files to EC2"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/app
- name: Executing node
  shell: |
    cd /home/ubuntu/app
    pm2 stop default
    pm2 start npm -- start